### PR TITLE
Update index.xml

### PR DESCRIPTION
**Pull request by mngzir**
hDefines support vqmod 
For changes to the management template files

### CODE REVIEW

**Comment by adrianolmedo** [comment]
Thanks for checking, it will merge to the next version. This has led me to discover two other files into oc-includes/osclass/helpers / that also need it, such as hSecurity.php and hUtils.php

**Comment by mngzir** [comment]
If you change the hSecurity.php file You need to modify the following files as well
oc-admin/login.php
oc-includes/osclass/controller/login.php

**Comment by adrianolmedo** [comment]
Sorry for responding late, I am working on another version of other Osclass projects and I was in a break.

All this will be noted and included in the next version. I will be testing those files.

**Comment by adrianolmedo** [comment]
> If you change the hSecurity.php file You need to modify the following files as well
> oc-admin/login.php
> oc-includes/osclass/controller/login.php

> Thanks for checking, it will merge to the next version. This has led me to discover two other files into oc-includes/osclass/helpers / that also need it, such as hSecurity.php and hUtils.php

When I wrote that, I was testing in Osclass 3.8

In Osclass 3.9 these files no longer have require_once

**Comment by adrianolmedo** [comment]
> hDefines support vqmod
> For changes to the management template files

I have been testing some things more, all it's Ok. I am really grateful for your collaboration.

You have account in https://forums.osclasscommunity.com/? Mail me your username.

**Comment by mngzir** [comment]
You did the main thing I'm happy to be able to help, check again and do more tests to fix the bug.
With this extension we can make many changes to the system kernel
I registered at forums.osclasscommunity.com but no activation email was sent??

**Comment by adrianolmedo** [comment]
I didn't receive the activation email either.

So my account is not activated either.

I'm just careful not to forget the password.

**Comment by mngzir** [comment]
I can't login to that site
I'm looking for a contact with the site's administrators

**Pull request merged**
